workers:           2      # Number of workers for dataloader
batch_size:        128    # Batch size during training
image_size:        128     # Spatial size of training images. 
                          # All images will be resized to this size using a transformer.
num_channels:      3      # Number of channels in the training images.
z_dim:             100    # Size of z latent vector (size of generator input)
g_channels:        128     # Size of feature maps in generator
d_channels:        128     # Size of feature maps in discriminator
num_epochs:        200    # Number of training epochs
lr:                0.0002 # Learning rate for optimizers
beta1:             0.5    # Beta1 hyperparameter for Adam optimizers
ngpu:              1      # Number of GPUs available. Use 0 for CPU mode.
log_interval:      100    # Interval between successive logs
sampling_interval: 1      # Interval between image generations during training (in epochs)
checkp_interval:   2      # Interval between saving model checkpoints (in epochs)
experiment_name: 'DCGAN_pytorch_tutorial_128x128_01' # Name of the experiment.
dataset_path:    "/home/datasets/celeba_50k" # Root directory for dataset
dataset:         "CelebA"  # Dataset used for training the models
