epochs:              200    # Number of training epochs
batch_size:          128    # The batch size
latent_dim:          100    # Dimension of the latent space
img_size:            28     # Image size
g_neurons_per_layer: [256, 512, 1024] # Number of neurons in generator Linear layers,
                            # except the last layer that has img_size*img_size
d_neurons_per_layer: [512, 256, 1] # Number of neurons in discriminator Linear layers
lr:                  0.0005 # Adam optimizer learning rate
beta1:               0.5    # Adam decay of first order momentum of gradient
beta2:               0.999  # Adam decay of first order momentum of gradient
n_cpus:              4      # Number of cpu threads to use during batch generation
channels:            1      # Image channels
sampling_interval:   1000   # Interval between image generations during training
log_interval:        100    # Interval between successive logs
checkp_interval:     1      # Interval between saving model checkpoints (in batches)
data_dir_root:       "OUR_DATASETS_DIR"  # directory where is the MNIST dataset
experiment_name:     "GAN_mnist_v2_04" # File where trained models will be saved
dataset:             "MNIST"           # Dataset used for training the models