batch_size:            64      # batch size during training.
image_size:            128     # spatial size of training images;
                               # all images will be resized to this size using a transformer.
channels:              3       # Number of channels in the training images.
c_hidden_dim:          64      # Number of channels in critic hidden layers.
g_hidden_dim:          64      # Number of channels in generator hidden layers.
c_conv_layers:         5       # Number of conv layers in the critic.
g_conv_layers:         5       # Number of conv layers in the generator.
c_min_feature_size:    4       # Minimum feature size in conv layers of the critic.
g_min_feature_size:    4       # Minimum feature size in conv layers of the generator.
crop_size:             128     # Size used to crop original images of the dataset.
z_dim:                 100     # size of z latent vector (size of generator input).
ncritic:               2       # Critic optimization iterations per generator iteration.
gradient_penalty:      v1      # Constrain critic using gradient penalty ('v1' or 'v2') or clipping ('None').
lambda_gp:             10      # Gradient penalty weight.
lr_c:                  0.0002  # Learning rate for critic optimizer.
lr_g:                  0.0002  # Learning rate for generator optimizer.
beta1:                 0.5     # beta1 hyperparameter for Adam optimizers.
beta2:                 0.99    # beta2 hyperparameter for Adam optimizers.
manual_seed:           42      # manual seed.
epochs:                200     # Number of training epochs.
log_interval:          100     # Interval between successive logs (in iterations).
sampling_interval:     1       # Interval between image generations during training (in epochs).
checkp_interval:       5       # Interval between saving model checkpoints (in epochs).
experiment_name:       "WGANGP_CelebA_128x128_05" # Name of the experiment.
dataset_path:          "/home/datasets/celeba/balanced"  # Root directory for dataset.
dataset:               "CelebA balanced"  # Dataset used for training the models.
