# Takes as input an unordered embedding dataset along with metadata generated by 
# clip-retrieval and reorders the embeddings to match the order of the image dataset.

mkdir OUR_DATASETS_DIR/laion_aesthetics_65p_embeds_v3/img_emb_ordered
mkdir OUR_DATASETS_DIR/laion_aesthetics_65p_embeds_v3/text_emb_ordered

reorder-embeddings reorder \
	--embeddings-folder=OUR_DATASETS_DIR/laion_aesthetics_65p_embeds_v3/img_emb \
	--metadata-folder=OUR_DATASETS_DIR/laion_aesthetics_65p_embeds_v3/metadata \
	--output-folder=OUR_DATASETS_DIR/laion_aesthetics_65p_embeds_v3/img_emb_ordered \
	--index-width=4 \
	--output-shard-width=5 \
	--limit=62 \
	--run-concurrent=1 \
	--verbose=true

reorder-embeddings reorder \
	--embeddings-folder=OUR_DATASETS_DIR/laion_aesthetics_65p_embeds_v3/text_emb \
	--metadata-folder=OUR_DATASETS_DIR/laion_aesthetics_65p_embeds_v3/metadata \
	--output-folder=OUR_DATASETS_DIR/laion_aesthetics_65p_embeds_v3/text_emb_ordered \
	--index-width=4 \
	--output-shard-width=5 \
	--limit=62 \
	--run-concurrent=1 \
	--verbose=true

# mv img_emb_0*.npy text_emb_*.npy